name: ${project.name}
main: com.untamedears.PrisonPearl.PrisonPearlPlugin
version: ${project.version}
softdepend: [Mercury, NameLayer, CombatTag, WorldBorder, CombatTagPlus, BetterShards]
description: PrisonPearl makes it so players can imprison each other (called 'pearling') in The End. Kill someone with an ender pearl in your hotbar and they'll be stuck in The End and tied to the pearl. Destroying the pearl releases them.
commands:
   pplocate:
      description: Locates your prison pearl
      usage: /<command>
      aliases: ppl
      permission: prisonpearl.normal.pplocate

   ppfeed:
      description: Feeds prison pearls
      usage: /<command>
      permission: prisonpearl.admin

   pplocateany:
      description: Locates any prison pearl in the world
      usage: /<command> player
      permission: prisonpearl.pplocateany

   ppfree:
      description: Frees a prison pearl
      usage: /<command> [player]
      aliases: ppf
      permission: prisonpearl.normal.ppfree

   ppfreeany:
      description: Frees any prison pearl in the world
      usage: /<command> player
      permission: prisonpearl.ppfreeany
      

   ppsummon:
      description: Summons a player from their prison pearl, requiring them to stay within range of their pearl
      usage: /ppsummon [player] [range]
      aliases: pps
      permission: prisonpearl.normal.ppsummon

   ppreturn:
      description: Returns a summoned player back to their prison pearl
      usage: /ppbanish [player]
      aliases: ppr
      permission: prisonpearl.normal.ppreturn

   ppkill:
      description: Instantly kills a summoned player, sending them back to their prison pearl
      usage: /ppkill [player]
      aliases: ppk
      permission: prisonpearl.normal.ppkill

   ppsave:
      description: Saves all prisonpearl related data to disk
      usage: /ppsave
      permission: prisonpearl.ppsave

   ppimprisonany:
      description: Imprisons any player in the world
      usage: /ppimprisonany player
      permission: prisonpearl.ppimprisonany

   ppbroadcast:
      description: Broadcast your pplocate commands to another player
      usage: /ppbroadcast player
      alias: ppb
      permission: prisonpearl.normal.ppbroadcast

   ppconfirm:
      description: Confirm reception of pplocate commands from a player
      usage: /ppconfirm [player]
      permission: prisonpearl.normal.ppconfirm

   ppsilence:
      description: Silence reception of pplocate commands from player
      usage: /ppsilence player
      permission: prisonpearl.normal.ppsilence

   pploadalts:
      description: reload alt lists from file
      usage: /pploadalts
      permission: prisonpearl.pploadalts

   ppcheckall:
      description: checkban all accounts
      usage: /ppcheckall
      permission: prisonpearl.ppcheckall

   ppcheck:
      description: checkban the player
      usage: /ppcheck [player]
      permission: prisonpearl.ppcheck

   ppsetdist:
      description: Sets distance prisoner can move.
      permission: prisonpearl.normal.ppsetdist

   ppsetdamage:
      description: Sets damage prisoner receives.
      permission: prisonpearl.normal.ppsetdamage

   pptogglespeech:
      description: Toggles whether prisoner can talk in public chat.
      permission: prisonpearl.normal.pptogglespeech

   pptoggledamage:
      description: Toggles whether prisoner can damage players and mobs.
      permission: prisonpearl.normal.pptoggledamage

   pptoggleblocks:
      description: Toggles whether prisoner can break blocks.
      permission: prisonpearl.normal.pptoggleblocks

   ppsetmotd:
      description: Sets prisoner's MOTD.
      permission: prisonpearl.normal.ppsetmotd
      
   ppgetalts:
      description: Gets a list of the players associated accounts.
      usage: /ppgetalts [playername]
      permission: prisonpearl.getalts

   ppsetalts:
      description: Allows people to add players to the excluded_alts.txt.
      usage: /ppsetalts [playername] [confirmedalt1] [confirmedalt2] etc....
      permission: prisonpearl.setalts

   ppban:
      description: Bans a player's alt list.
      usage: /ppban <player>
      permission: prisonpearl.banalts

   ppunban:
      description: Unbans a player's alt list.
      usage: /ppunban <player>
      permission: prisonpearl.unbanalts
   ppwb:
      description: add or remove a while listed location.
      usage: /ppwb <add/remove> <x> <y> <z>
      permission: prisonpearl.ppwb

permissions:
   prisonpearl.normal.pplocate:
      description: Gives access to the pplocate command.
      default: true

   prisonpearl.pplocateany:
      description: Gives access to the pplocateany command.
      default: false

   prisonpearl.normal.ppfree:
      description: Gives access to the ppfree command.
      default: true

   prisonpearl.ppfreeany:
      description: Gives access to the ppfreeany command.
      default: false

   prisonpearl.normal.ppsummon:
      description: Gives access to the ppsummon command.
      default: true

   prisonpearl.normal.ppreturn:
      description: Gives access to the ppreturn command.
      default: true

   prisonpearl.normal.ppkill:
      description: Gives access to the ppkill command.
      default: true

   prisonpearl.ppsave:
      description: Gives access to the ppsave command.
      default: false

   prisonpearl.normal.ppbroadcast:
      description: Gives access to the ppbroadcast command.
      default: true

   prisonpearl.normal.ppconfirm:
      description: Gives access to the ppconfirm command.
      default: true

   prisonpearl.normal.ppsilence:
      description: Gives access to the ppsilence command.
      default: true

   prisonpearl.pploadalts:
      description: Gives access to the pploadalts command.
      default: false

   prisonpearl.ppcheckall:
      description: Gives access to the ppcheckall command.
      default: false

   prisonpearl.ppcheck:
      description: Gives access to the ppcheck command.
      default: false

   prisonpearl.kill:
      description: Gives access to the kill command.
      default: false
      
   prisonpearl.getalts:
      description: Gives access to the ppgetalts command.
      default: false
      
   prisonpearl.setalts:
      description: Gives access to the ppsetalts command.
      default: false

   prisonpearl.normal.ppsetdist:
      description: Gives access to the ppsetdist command.
      default: true

   prisonpearl.normal.ppsetdamage:
      description: Gives access to the ppsetdamage command.
      default: true

   prisonpearl.ppimprisonany:
      description: Gives access to the ppsetdamage command.
      default: false

   prisonpearl.normal.ppsetmotd:
      description: Gives access to the ppsetmotd command.
      default: true

   prisonpearl.normal.pptogglespeech:
      description: Gives access to the pptogglespeech command.
      default: true

   prisonpearl.normal.pptoggledamage:
      description: Gives access to the pptoggledamage command.
      default: true

   prisonpearl.normal.pptoggleblocks:
      description: Gives access to the pptoggleblocks command.
      default: true

   prisonpearl.normal.pearlplayer:
      description: Let's players pearl other players.
      default: true

   prisonpearl.unbanalts:
      default: op

   prisonpearl.banalts:
      default: op
   
   prisonpearl.wb:
      default: op
      
   prisonpearl.admin:
      default: op

   prisonpearl.*:
      description: Gives full access to PrisonPearl commands
      default: op
      children:
         prisonpearl.pplocateany: true
         prisonpearl.ppfreeany: true
         prisonpearl.ppimprisonany: true
         prisonpearl.ppsave: true
         prisonpearl.getalts: true
         prisonpearl.setalts: true
         prisonpearl.pploadalts: true
         prisonpearl.pplistbans: true
         prisonpearl.banalts: true
         prisonpearl.unbanalts: true
         prisonpearl.wb : true
